### ISSUE TITLE
Delay bar sprite for delay 7 missing

### ISSUE THREAD

**Issue by tomatocurry1** [PleasingFungus/Silicon-Zeroes#106]
![delay bar sprite](https://user-images.githubusercontent.com/4267815/31100857-1391665c-a799-11e7-9dac-c79488a85032.png)

As the bug report says, the delay bar sprite 7 is missing apparently.

**Comment by PleasingFungus** [comment]
Already fixed in 5f13aaa41; will be out in a hotfix later today.

Very sorry for the trouble!

**Comment by tomatocurry1** [comment]
Alright thanks!
