### ISSUE TITLE
Multiply: Ideal 18 modules (instead of 20)

### ISSUE THREAD

**Issue by mickael9** [PleasingFungus/Silicon-Zeroes#108]
![multiply](https://user-images.githubusercontent.com/341358/31152303-c18aaa90-a89b-11e7-9a4d-eb1875136d8d.png)

[puzz-Multiply.mftsv.txt](https://github.com/PleasingFungus/Silicon-Zeroes/files/1354108/puzz-Multiply.mftsv.txt)

**Comment by PleasingFungus** [comment]
I intentionally have some of the 'ideals' higher than the lowest possible, so that the 'ideal all' achievement is possible for a human being to complete.

Nice work, though :)

**Comment by PleasingFungus** [comment]
Renamed 'ideal' to 'goal' for the next update, in adfc1b71.
