### ISSUE TITLE
Better keyboard layout support

### ISSUE THREAD

**Issue by mickael9** [PleasingFungus/Silicon-Zeroes#109]
Quick access keys (1..4) do not work on a French AZERTY keyboard, and the q, w, e, ... shortcuts should reflect the user's keyboard layout (a, z, e, ...).

Since you're using SDL2, this should be fairly easy to fix:
- Use scancodes to match the keys (`SDL_SCANCODE_Q`, `SDL_SCANCODE_1`, etc.)
- Get the layout key names for the q, w, e... scancodes using `SDL_GetKeyName(SDL_GetKeyFromScancode(...))` and use that in the UI

**Comment by PleasingFungus** [comment]
Thanks for suggesting the solution! Will take a look soon.

**Comment by mickael9** [comment]
By the way, the number keys are not problematic anymore since SDL 2.0.6 (and haven't ever been on Windows): https://hg.libsdl.org/SDL/rev/27eb9a10002c

You might still want to add a manual check to support older SDL versions (current steam runtime seems to be at 2.0.5)

**Comment by PleasingFungus** [comment]
I'm still on 2.0.4 or 2.0.5 myself, so I might have to update.

**Comment by PleasingFungus** [comment]
Should be resolved in commits 57f499fbe through c5159e3b. Thanks for reporting! Fun to work through.

Question: As a french keyboard user, is it idiomatic/normal to display '1'/'2'/etc for number row hotkeys, even when you don't have to press Shift to activate them? The alternative is rendering é for '2', and my font doesn't support extended ASCII, so it'd have to be "e`"...
