### ISSUE TITLE
Incorrect Goal for Highspeed: Clock

### ISSUE THREAD

**Issue by buckle2000** [PleasingFungus/Silicon-Zeroes#126]
My solution:
- number 1
- 2 adders
- a latcher

Result:
- Time: 12 mTicks
- Modules: 5

Goal:
- Time: 18 mTicks
- Modules: 3

**Comment by buckle2000** [comment]
I can make a faster solution!

**Comment by Spartelfant** [comment]
Many of the later puzzles have multiple solutions, where one solution may yield a low module count while requiring more processing time, while another solution can achieve a faster performance at the cost of using more modules.
So what you observed is - as far as I can tell - not a bug.

I'd say it's only a bug (or rather an oversight) if you had found a solution that was better in both mTickes **and** module count.

**Comment by buckle2000** [comment]
OK
