### ISSUE TITLE
Crash on completing Alternator puzzle

### ISSUE THREAD

**Issue by e2m4n** [PleasingFungus/Silicon-Zeroes#138]
![image](https://user-images.githubusercontent.com/18171271/145324085-6a8830a0-d41d-4440-a691-a0d02ce0b93a.png)
![image](https://user-images.githubusercontent.com/18171271/145324170-d1540ce0-e159-4c58-b3ad-f3971bb58ad8.png)

**Comment by PleasingFungus** [comment]
Thanks for reporting! Does this happen every time you beat the level?

**Comment by e2m4n** [comment]
Thanks for the lightning-fast response!
Yes it happens every time (have tried three times so far).
An interesting side-effect is that the 'play' button has vanished after the first time it happened.
Another thing is that, when reloading, the puzzle is empty, and it won't let me add a writer - I have to reset the puzzle to get the writer module back.

**Comment by PleasingFungus** [comment]
Hm, that's very strange. If you delete the file listed there (`profiles/profile0/successful/puzz-Alternator.mftsv`), does anything change? (That `profiles` directory is in the game directory itself on Windows/Linux and in `~/Library/Application Support/Silicon Zeroes/` on OSX, if I remember correctly.)

**Comment by e2m4n** [comment]
Yes that fixed it! Great, thanks! (and now I see that the goal is 6 modules, so going to have to spend a bit more time on that puzzle, grrrr ;-) )

**Comment by PleasingFungus** [comment]
Good luck! :)

**Comment by e2m4n** [comment]
Thanks! I just solved it with six modules - I'm not sure what i was thinking before! (In my defence it's very late here in Europe :-) )
I'm really enjoying the game, btw - I'm a big fan of the Zachtronics games and Silicon Zeroes is one of the few games which I think is worthy of mentioning in the same breath as Shenzhen I/O and TIS-100 - you've done a great job!

**Comment by PleasingFungus** [comment]
Aw, thanks! Really glad you like it. :)
