### ISSUE TITLE
Crash at startup on linux

### ISSUE THREAD

**Issue by jolitti** [PleasingFungus/Silicon-Zeroes#139]
![image](https://user-images.githubusercontent.com/85450809/171867698-18d71b76-d4af-4e4b-8e82-d89d7f98ff12.png)

Context:
I'm playing on pop os 22.04 (an os based on ubuntu) on a thinkpad x240, steam is in offline mode

**Comment by PleasingFungus** [comment]
Ah, sorry to hear this! Does it crash consistently? Does your sound work for other games? (I don't have a Linux build avaialable, so this is pretty tricky for me to debug.)

**Comment by jolitti** [comment]
I've discovered that the crash only happens when i don't have headphones plugged into the pc i'm playing on. There might be an issue with my audio board, but the sound from other sources is fine even from the built-in speakers.

I'm really sorry for having found out about this bug, this must be what game devs have nightmares about

**Comment by PleasingFungus** [comment]
No worries! Thanks for reporting, glad you sorted it out. :)

**Comment by jolitti** [comment]
I'll close this issue as it's probably dependent on some idiosyncrasy on my computer
