### ISSUE TITLE
Crash on solving the Negate LateHours puzzle.

### ISSUE THREAD

**Issue by ddragon15** [PleasingFungus/Silicon-Zeroes#140]
Did nothing special, negating by draging the cable from a Equals-Module to an Subtract module which i fed 1 into the upper slot when it happend. It crashed and kinda corrupted the game file. It still solves all puzzles i already did. Save files are still there but it deleted all pattern and the buttons to switch between chapters are not showing anymore.

The error.txt log:
2941368: VERSION: 1.2.0.1-gae1a095d-S ERROR: Creating texture for wire: SDL ERROR (CreateTexture(D3DPOOL_DEFAULT): INVALIDCALL)
1604791: VERSION: 1.2.0.1-gae1a095d-S ERROR: Error loading successful after beating puzzle: invalid save file profiles/profile0/successful/puzz-Negate.mftsv (magic string not found)

![grafik](https://user-images.githubusercontent.com/21277566/210242328-cae0102a-ea3d-4d0d-8446-ba41ede0d55b.png)

**Comment by PleasingFungus** [comment]
Sorry about that! If you delete the file it mentions, `profiles/profile0/successful/puzz-Negate.mftsv`, does that fix the issue? (If you're on OS X, that'll be in `~/Library/Application Support/Silicon Zeroes/`; otherwise, it should be in the game directory, iirc.)

**Comment by ddragon15** [comment]
No worries 😃 thanks for the fast response.

Deleting the file didn't fixe the issue, but it can be solved by starting on a new profile and copying all folders except for global over. Palettes are still gone, but on opening a mission it instantly recognizes the old setup and sends me to the success screen.
So no harm done 😉 and a big thanks for keeping the saves so open to temper with so i could repair them myself.

**Comment by ddragon15** [comment]
just FYI 😅 found another one
![grafik](https://user-images.githubusercontent.com/21277566/210434593-e293049d-8fa4-4f52-b951-797c62589294.png)

errorLog:

> 1450539: VERSION: 1.2.0.1-gae1a095d-S ERROR: Error loading successful after beating puzzle: invalid save file profiles/profile0/successful/puzz-MicroCPU.mftsv (magic string not found)

**Comment by PleasingFungus** [comment]
Hm, that's quite unfortunate. Was there another 'creating texture' error beforehand?
