### ISSUE TITLE
The ideal of "Shift One" is 150 ticks, but I made a 144.

### ISSUE THREAD

**Issue by Pouf842** [PleasingFungus/Silicon-Zeroes#29]
![image](https://user-images.githubusercontent.com/2690188/28072566-c697112a-6653-11e7-9a4b-cd9f2075d187.png)

[puzz-Shift One.zip](https://github.com/PleasingFungus/Silicon-Zeroes/files/1139136/puzz-Shift.One.zip)

**Comment by PleasingFungus** [comment]
Added in cde13ad, thanks!
