### ISSUE TITLE
Different values briefly appears in modules when clicking "Test".

### ISSUE THREAD

**Issue by Pouf842** [PleasingFungus/Silicon-Zeroes#34]
Not really an issue, but when I click Test, the values in the modules briefly change (during the fade to black). When the test begins (after the fade), they are back to "normal".

Seem to be the last values of the last test set that stick in after the actual test by the algorithm.

I have noticed this in Spares, but I guess it's in every levels.

**Comment by Pouf842** [comment]
And now I'm in "Validation", and I get that this is on purpose.

Sorry.

**Comment by PleasingFungus** [comment]
Hey, no worries - that's why I added the level! :)
