### ISSUE TITLE
(Trying to) Overlap does not color modules in red anymore.

### ISSUE THREAD

**Issue by Pouf842** [PleasingFungus/Silicon-Zeroes#35]
Numbers are fine. Others modules keep their color when overlapping.

**Comment by PleasingFungus** [comment]
Might be a Windows-only issue? Can't reproduce this on OSX.

**Comment by PleasingFungus** [comment]
Can't reproduce on windows, either.

**Comment by Pouf842** [comment]
Let's assume it was anecdotal, or that it was fixed by side-effects on your last fixes. I'm closing it, and will re-open it if it happens again.

**Comment by Pouf842** [comment]
I didn't dream it ! Proof !

It may be related to #24, because as you can see, it's happening at the same time.

And that's a long shot, but maybe it has something to do with Alt-tabing ? (although, I'm in windowed, here...). I don't know...

![image](https://user-images.githubusercontent.com/2690188/28614348-ce85caf4-71f5-11e7-8763-89ee6b2d5d09.png)

**Comment by Pouf842** [comment]
Note that the buggy behavior stucks all through the game : once it happened, it does even after changing level.

**Comment by PleasingFungus** [comment]
Yeah, probably the same bug as #24. I'll see if I can duplicate & fix it for the next release.
