### ISSUE TITLE
Made a Par 120 ticks instead of 140 in "Costs"

### ISSUE THREAD

**Issue by Pouf842** [PleasingFungus/Silicon-Zeroes#39]
![image](https://user-images.githubusercontent.com/2690188/28161463-e32b4100-67c3-11e7-95e0-790f25f01b95.png)

**Comment by PleasingFungus** [comment]
Something's very wrong here - I have a completely different Test 1.

![screen shot 2017-07-13 at 8 58 29 am](https://user-images.githubusercontent.com/1192475/28175611-8e3440c6-67a9-11e7-9cea-e9bfca9a30ac.png)

Nice solution, though you could get it a little faster...

**Comment by PleasingFungus** [comment]
Fixed in b8fb1f1.
