### ISSUE TITLE
Could hitting Z or Y in Test mode switch back to Edit mode, please ?

### ISSUE THREAD

**Issue by Pouf842** [PleasingFungus/Silicon-Zeroes#42]
Many times after testing a modification, I'd like to cancel it, so as soon as the test is finished, I hit Z, but that does not work. I'm forced to pick my mouse and click on the button.

**Comment by PleasingFungus** [comment]
Hit Tab?

**Comment by Pouf842** [comment]
Ok, I'll settle with that.
