### ISSUE TITLE
Not sure those different colors of wires are intended.

### ISSUE THREAD

**Issue by Pouf842** [PleasingFungus/Silicon-Zeroes#50]
Wires between my RegFile and the I-Sel should be all grey, right ? (I verified each wire, they are each between an output slot of the RegFile and an Input slot of a I-Sel)

![image](https://user-images.githubusercontent.com/2690188/28316919-0d72fce6-6bc5-11e7-8070-d1b80d5ab1c7.png)

**Comment by Pouf842** [comment]
It corrected itself after a few actions (moving some modules, adding an Adder. I didn't catch which action did the trick).

**Comment by PleasingFungus** [comment]
This is intended, just not explained.

Registers and Latches currently output based on whatever they have stored - if they store a value from Instruction Decode's Source, for example, then their output will be that same pink.

This is mainly supposed to help with late-game multi-stage levels, so you can still see source/target/destination being held by registers in later parts of the machine. It's a bit weirder in regfiles, and probably not particularly helpful.

It 'corrected itself' after you left the sim.

**Comment by Pouf842** [comment]
Oh, okay, nice !
