### ISSUE TITLE
"Delay write" is not placed right on the board (it only unlocks after "Delay latch")

### ISSUE THREAD

**Issue by Pouf842** [PleasingFungus/Silicon-Zeroes#51]
![image](https://user-images.githubusercontent.com/2690188/28317048-a6c42f1e-6bc5-11e7-8529-8c14318513f4.png)

**Comment by PleasingFungus** [comment]
That board image is wrong. It should look like this:

![screen shot 2017-07-18 at 9 08 16 am](https://user-images.githubusercontent.com/1192475/28327571-b09d3e7c-6b98-11e7-9e24-d86ef6adf03d.png)

I don't understand why your build has the wrong image... possibly I screwed up when uploading it?

**Comment by Pouf842** [comment]
Okay, I'll check with the next build.
