### ISSUE TITLE
Crash : "no input for powered latch (!)" 

### ISSUE THREAD

**Issue by Pouf842** [PleasingFungus/Silicon-Zeroes#52]
1820886: VERSION: 0.8.0.1-g02542c3 ERROR: no input for powered latch (!)

I had just removed a wire from a latch input, and pressed "Test".

I was going to make a screenshot, but as I used Alt+PrintScreen instead of PrintScreen, the Alt key shut the game down.

**Comment by Pouf842** [comment]
Reproducible. Here is (what I think is the save).
[puzz-Delay-Acc.zip](https://github.com/PleasingFungus/Silicon-Zeroes/files/1155860/puzz-Delay-Acc.zip)

**Comment by PleasingFungus** [comment]
Sorry, how exactly do I reproduce this? There's only one wire in the save you provided, and deleting it doesn't seem to do anything.

![screen shot 2017-07-18 at 9 17 17 am](https://user-images.githubusercontent.com/1192475/28327991-e87e7db4-6b99-11e7-8a08-36a9b5489a0f.png)

**Comment by Pouf842** [comment]
Well, I just have to run the game, load the level and press Test.

I download the itch.io build again, unzipped it, put my save (from this post), launched the game and clicked "Test". Note that I also had the old board image (with the misplaced "Delay write").

Most likely, the itch.io build is not up to date. Where can I check the build version of my game ?

**Comment by PleasingFungus** [comment]
Oh, you didn't say anything about hitting Test! I'll try that in a moment.

There's not really anywhere to check the build version in-game right now, other than the screen you get when you crash. I should fix that...

**Comment by PleasingFungus** [comment]
Crash fixed in 1842aac9, thanks! It would occur any time you had a latch or register without an input & had the clock period set to < 3.

(Viewing the build version ingame was added in 082254dc.)
