### ISSUE TITLE
Par 14$ on "Fast two"

### ISSUE THREAD

**Issue by Pouf842** [PleasingFungus/Silicon-Zeroes#54]
![image](https://user-images.githubusercontent.com/2690188/28319248-a5a790fa-6bcd-11e7-8b13-2f90e0952469.png)

**Comment by Pouf842** [comment]
Save file : 

[puzz-Fast Two.zip](https://github.com/PleasingFungus/Silicon-Zeroes/files/1155993/puzz-Fast.Two.zip)

**Comment by PleasingFungus** [comment]
This one's already changed for the next build - it's possible to get $12, actually :)
