### ISSUE TITLE
Par 150 ticks on "Products"

### ISSUE THREAD

**Issue by Pouf842** [PleasingFungus/Silicon-Zeroes#55]
I realize maybe it would be easier for you to have the save file. I'll join them as well from now on.
[puzz-Products.zip](https://github.com/PleasingFungus/Silicon-Zeroes/files/1155992/puzz-Products.zip)

![image](https://user-images.githubusercontent.com/2690188/28319650-c48298ac-6bce-11e7-92bd-5f8970546096.png)

**Comment by PleasingFungus** [comment]
Nice! Change made in aeaa3b5.
