### ISSUE TITLE
A palette I can place in a level won't place in another

### ISSUE THREAD

**Issue by Pouf842** [PleasingFungus/Silicon-Zeroes#56]
Here's the palette :
[group-1.zip](https://github.com/PleasingFungus/Silicon-Zeroes/files/1156024/group-1.zip)

I can place it in some level, for instance, "Arith-CPU", but in others ("Delay CPU"), the 2 I-Sel at far right overlap.

I suppose this is due to the difference of size of the modules between non-delay and delay levels.

**Comment by PleasingFungus** [comment]
Fixed in 64112128, thanks!
