### ISSUE TITLE
Par $13 and Par 114 ticks on "Delay CPU" (instead of $17 and 132)

### ISSUE THREAD

**Issue by Pouf842** [PleasingFungus/Silicon-Zeroes#58]
The 114 ticks solution is the same with all modules set to fast.

Might just be an oversight or a mistake of yours, since this solution seems pretty basic to me.

![image](https://user-images.githubusercontent.com/2690188/28567720-99cc7afa-7133-11e7-834a-c169caa073fe.png)

[puzz-Delay CPU.zip](https://github.com/PleasingFungus/Silicon-Zeroes/files/1172817/puzz-Delay.CPU.zip)

**Comment by PleasingFungus** [comment]
Yours was slightly more optimized than mine; mine had the register between the reader & idecoder, instead of after the idecoder.

Fixed in 8fdc850a, thanks!
