### ISSUE TITLE
Par 153/32$ ticks on Fast 2-2 (instead of 156/56$)

### ISSUE THREAD

**Issue by Pouf842** [PleasingFungus/Silicon-Zeroes#60]
153 ticks :
![image](https://user-images.githubusercontent.com/2690188/28618383-78456d70-7204-11e7-85c4-f657121d8afb.png)

[puzz-Fast 2-2.zip](https://github.com/PleasingFungus/Silicon-Zeroes/files/1176374/puzz-Fast.2-2.zip)

32$ :
![image](https://user-images.githubusercontent.com/2690188/28624695-34388b56-721a-11e7-8de6-55ba86126f59.png)
[puzz-Fast 2-2.zip](https://github.com/PleasingFungus/Silicon-Zeroes/files/1176766/puzz-Fast.2-2.zip)

Also, question : How come your ideal cost (56$) is more than twice the ideal number of modules (25) ? Is it an error, or is it possible, and I just don't get how ?

**Comment by PleasingFungus** [comment]
Probably an error! Doesn't much matter now; the cost mechanic is gone for the next release.

New time par added in 33bb0693, thanks!
