### ISSUE TITLE
Crash when dragging the scroll handle in test mode.

### ISSUE THREAD

**Issue by Pouf842** [PleasingFungus/Silicon-Zeroes#66]
The level was "Ones".
No message, no errors text file, just "Process has stopped responding" window.
Couldn't reproduce it.

Here is the design. I just had removed a 1 Num-module connected to the writer value input and rewired to use the left-most 1 Num-module instead.

[puzz-Ones.zip](https://github.com/PleasingFungus/Silicon-Zeroes/files/1220362/puzz-Ones.zip)

Game version is 0.8.2.0-ge46a76b

No more information. Sorry.

**Comment by PleasingFungus** [comment]
I don't understand - what scroll handle? Was this part of the window, something inside the game...?

**Comment by PleasingFungus** [comment]
Managed to reproduce this on my first go, but not afterward. Very strange.

**Comment by PleasingFungus** [comment]
Fixed in bc26f44f, thanks! (This occurs when you beat a level with a different solution than the old one, basically.)
