### ISSUE TITLE
Par 12 instead of 19 on "Delay jump"

### ISSUE THREAD

**Issue by Pouf842** [PleasingFungus/Silicon-Zeroes#68]
[puzz-Delay Jump.zip](https://github.com/PleasingFungus/Silicon-Zeroes/files/1220666/puzz-Delay.Jump.zip)

![image](https://user-images.githubusercontent.com/2690188/29252403-c75fb1de-8066-11e7-8277-f5c2ab941cb3.png)

**Comment by PleasingFungus** [comment]
Fixed in c986dcb6 (by tightening the time requirements from 29 mTicks/instr to 25), thanks!

**Comment by Pouf842** [comment]
Damn. I have to find a new solution, and play the game some more, then.

Oh, well =D
