### ISSUE TITLE
Par 13 instead of 14 on Delay-CPU

### ISSUE THREAD

**Issue by Pouf842** [PleasingFungus/Silicon-Zeroes#73]
![image](https://user-images.githubusercontent.com/2690188/29689756-a75f5f94-8924-11e7-9b68-80380513dba6.png)

[puzz-Delay CPU.zip](https://github.com/PleasingFungus/Silicon-Zeroes/files/1250290/puzz-Delay.CPU.zip)

**Comment by PleasingFungus** [comment]
Hm. This doesn't work for me - can you post a screenshot with the memory included?

**Comment by Pouf842** [comment]
Sure :

![image](https://user-images.githubusercontent.com/2690188/29690505-8c278ea6-8927-11e7-8f6c-d13c52f000af.png)

**Comment by PleasingFungus** [comment]
Hrm, that screenshot is of a different (much faster) solution. I tried yours and it ran out of time for me - can you send a screenshot of the slower solution (from the first screenshot) setting memory correctly?

**Comment by Pouf842** [comment]
Yeah, sorry, I've tried to beat the ticks ideal in between. My bad.

But, now when I come back to the old solution, it is indeed too slow...

My only guess is that a bug made the time limit not respected by the tests, because I'm sure the solution worked, I had the finish screen.

I'll try and erase my save and redo the same solution in a first run. Maybe the bug will occur again...

**Comment by PleasingFungus** [comment]
Before erasing your save, try fiddling around with the test you're looking at?

**Comment by Pouf842** [comment]
Ok, I've made a new profile and get to that level again, and did the exact same solution. I now have a 13 modules/32 tick solution, which is fast enough :

![image](https://user-images.githubusercontent.com/2690188/29691748-b5a1ab36-892c-11e7-8cce-c23440e26117.png)

You can see the 32 at the bottom behind the finish screen.

Now, when I've passed the final video sequence and back to the level, my solution is now at 34 ticks, and therefore too slow.

![image](https://user-images.githubusercontent.com/2690188/29691801-f3995b96-892c-11e7-974c-27ccb09986fb.png)

**Comment by PleasingFungus** [comment]
That's seriously weird. Will investigate.

Thanks for finding this!

By 'made a new profile', do you actually mean you started from the beginning of the game and got back to this puzzle that quickly, or did you just erase the save for this puzzle or something like that?

**Comment by Pouf842** [comment]
Exactly, I've quit the game, copied the save file from the old profile folder to the new one, erased Delay-CPU save in the new one, start the game, and went through all levels, loading the solutions and simply validating until I got to Delay-CPU. There, I built the same solution from scratch, and voila.

But again, you just have to empty the level, and redo it from scratch.

**Comment by PleasingFungus** [comment]
OK, that should be enough for me to replicate the problem, hopefully. I'll get back to you once I have a look at it.

**Comment by PleasingFungus** [comment]
Ohhhhh. Figured it out. The delay for the input/output selectors doesn't change correctly when you edit them; not until you reload the level.

Fun bug!

**Comment by PleasingFungus** [comment]
"why does the delay for input/output selectors vary by size?"

"it seemed like a good idea at the time"

**Comment by Pouf842** [comment]
I'm afraid this bug may have induced some ticks "Par" I've submitted to you... Gotta check'em all.

**Comment by PleasingFungus** [comment]
Yeah, good point. I check the tick-pars before I send them to you, but I could've run into the same bug while checking!

**Comment by PleasingFungus** [comment]
Core bug fixed in 4c1e35f4.
