### ISSUE TITLE
Level is not validate after quitting the module edition dialog box. Need to move the mouse for the validation to trigger.

### ISSUE THREAD

**Issue by Pouf842** [PleasingFungus/Silicon-Zeroes#74]
It's not really a bug, and most of the time, nobody would notice, because we tend to move the mouse often enough. Plus, it concerns only a few level at the beginning of the game. But sometimes, people would just click outside the dialog box and wait, and nothing would happen until they wonder why and move the mouse to try something else.

Could be disturbing.

**Comment by PleasingFungus** [comment]
Very subtle! Nice catch.

Fixed in 682dadea, thanks!
