### ISSUE TITLE
"Next step" sound does not end if it is interrupted by another one.

### ISSUE THREAD

**Issue by Pouf842** [PleasingFungus/Silicon-Zeroes#76]
How to reproduce :

- Click on "Next step" in test mode : "Next step" sound plays
- Quickly drag and drop a module before the "Next step" sound finishes. "Drag" and "drop" sounds play.
- "Next step" sound loop forever until you click the "Test" button.
- ?????
- Profit

**Comment by PleasingFungus** [comment]
Fixed in b484b853, thanks!
