### ISSUE TITLE
Is the ideal of "Deref-R" really 6 ?

### ISSUE THREAD

**Issue by Pouf842** [PleasingFungus/Silicon-Zeroes#80]
I've got an 8 solution, and I really don't see how I could get rid of any of my modules.
Also, is the "Branch" ideal really 15 ? I have 16, and there too don't see how to get rid of anything.

**Comment by PleasingFungus** [comment]
Deref-R is correct, Branch is wrong. Fixed the latter in 6eed7e2b, thanks!
