### ISSUE TITLE
Still no portrait at the end of some (all ?) bonus levels " (is it voluntary ?)

### ISSUE THREAD

**Issue by Pouf842** [PleasingFungus/Silicon-Zeroes#81]

**Comment by PleasingFungus** [comment]
Intended.

**Comment by Pouf842** [comment]
Ok, cool.

(Maybe you can make it more obvious ? Like a silhouette, or something like that ?)

**Comment by PleasingFungus** [comment]
I've thought about it, but that that would take art... :(

Perhaps some kind of 'no photo' or other text? I don't know. It's reasonable to try to clarify it somehow...
