### ISSUE TITLE
Par 22 instead of 23 for "Greater"

### ISSUE THREAD

**Issue by Pouf842** [PleasingFungus/Silicon-Zeroes#82]
I suppose it's the I-Sel before the writer that helped.

![image](https://user-images.githubusercontent.com/2690188/30164542-30345e74-93dd-11e7-86dc-4b3dfa4aed57.png)

**Comment by Pouf842** [comment]
I suppose it's the I-Sel before the writer that helped.

**Comment by PleasingFungus** [comment]
Nice work! Added in a6c6fa65.
