### ISSUE TITLE
Graphics parameters synchronisation (Steam cloud) is quite annoying.

### ISSUE THREAD

**Issue by Pouf842** [PleasingFungus/Silicon-Zeroes#86]
Could you not sync the graphics parameters on Steam cloud ? From one computer to the other, people could have different choices of resolution (I do) or Fullscreen/Windowed (I do), and would probably like not to change them again each time they switch computer.

What do you think ?

**Comment by PleasingFungus** [comment]
Good idea! I've pushed a possible fix - testing it now.

**Comment by Pouf842** [comment]
Same for the sound and music volumes.

**Comment by PleasingFungus** [comment]
Yep, I was also planning that. It should only sync the profiles directory and the profile.txt (the last active directory).

**Comment by PleasingFungus** [comment]
It might be working now, but it's hard for me to be sure, sorry...

**Comment by PleasingFungus** [comment]
It wasn't fixed; should actually be fixed in f9348af1. (Will be live shortly.)
