### ISSUE TITLE
Par 19 on Greater (instead of 22)

### ISSUE THREAD

**Issue by Pouf842** [PleasingFungus/Silicon-Zeroes#87]
Using the same counter to add to both operands.

![image](https://user-images.githubusercontent.com/2690188/30315374-02700eaa-97a4-11e7-8d46-fd2ef88216c0.png)

[puzz-Greater.zip](https://github.com/PleasingFungus/Silicon-Zeroes/files/1295221/puzz-Greater.zip)

**Comment by PleasingFungus** [comment]
Sorry, the build is out of date for this one. You can actually get this down to 17 modules!

Thanks for reporting :)

**Comment by Pouf842** [comment]
I hate you so much, right now... =P
