### ISSUE TITLE
Crash when register output is connected to "higher" input

### ISSUE THREAD

**Issue by Demki** [PleasingFungus/Silicon-Zeroes#89]
Version 1.0.0.1-g86e171f1  
Error: No infobox matching up to wire during populate display wires.  

Cause:  
When a register's last output is connected to a lower numbered input(say register 1 to input 0), and the register module is configured to a lower size, the game crashes with the above message.

Here's an image of when this occurs.  
![screenshot](https://user-images.githubusercontent.com/346170/30609198-6446cc06-9d83-11e7-96ed-dab99acd231d.png)

**Comment by PleasingFungus** [comment]
Great find! Working on it now.

**Comment by PleasingFungus** [comment]
Fixed in d896ff93! Will be working properly in the next build.

Thanks for reporting!
