### ISSUE TITLE
Numbers don't correspond to letters as expected

### ISSUE THREAD

**Issue by Luna-Rex** [PleasingFungus/Silicon-Zeroes#90]
I probably "solved" this one in a way that wasn't quite expected/optimal, but it still feels like unintentional behavior. Each letter seemed to be correspond to a number. However, they lose their encoding as letters when I attempt to flip it from Z to A, and get stored in memory as pure numbers, marking it as the wrong answer. Is this a bug?

[Image of the malformed output](https://i.imgur.com/PcUGgH5.png)

**Comment by PleasingFungus** [comment]
The intended behavior is that letters stay letters as long as the values stay between 0-26 (inclusive). There's no inherent 'modulo' behavior. (This isn't documented - I could probably improve on it!)

I'm not sure exactly what your machine is doing - how exactly are you trying to flip letters from Z to A?

**Comment by Luna-Rex** [comment]
It first checks if the input value is 0 and, if so, it feeds a -1 into an adder which adds 1 to it, making it 0, which should correspond to a space. (the process is a little awkward but it technically sends the right numerical value for a space)

It then checks if the input value is 26(or Z); if it is, the constant 1 from the counter is sent to the Writer instead of the input value.

In short, it seems sending anything but a modified input value to the writer causes it to get output as a number instead of a letter, regardless of being a value between 0-26. You can see this on the Memory Now page visible in the linked image above.

**Comment by PleasingFungus** [comment]
Should be clearer as of 12310c1b (next release). Thanks for reporting!
