### ISSUE TITLE
Write-Once Memory accepts multiple writes, possible validation race condition

### ISSUE THREAD

**Issue by KitsuneZeta** [PleasingFungus/Silicon-Zeroes#92]
This mostly affects the Sam puzzle "Collision" and specifically its first test.

In puzzles that claim to use Write-Once Memory, which is specifically noted to only accept one write per memory location, the simulator allows a second write to a memory location. The simulator automatically stops (and validation supposedly fails) whenever a value that isn't the goal value is written to a memory location.

The game is also inconsistent with this, as I only discovered it when returning to a previously-completed puzzle ("Collision", "solved" at one module under ideal) only to find that the validated solution fails on test 1 (and only test 1). The specifics of the solution suggest that it only passed validation once due to a race condition.

For clarity, the instruction set in memory in test 1 is as follows:

0 MSET 1 - 10
1 MSET 2 - 11
2 MSET 3 - 11
3 MSET 4 - 11
4 MSET 5 - 12

The Goal values are value 1 in memory location 10, 4 in location 11, and 5 in location 12.

The naive solution (given its predecessor) is to implement the standard counter-memory-reader starting at 0 and also have one run at an offset of +3 (so that instructions 0 and 3 are run simultaneously). This would write to memory in locations 10 and 11, which should lock them and block future writes. Then on the next cycle, instructions 1 and 4 would run, attempting to write 2 into 11 (which has already been written to and thus won't accept the new value) and 5 into 12 (which hasn't been written to).

This solution worked exactly once (and did result in my first under-ideal-modules solution). However, every other attempt at it caused it to fail on test 1 and ONLY on test 1. This suggests two issues:

1. Write-Once Memory accepts multiple writes (despite being specifically described as not doing so)
2. Validation with parallel memory writes is not deterministic (which means if an operation setting the final goal value occurs on the same step that an operation changing a correct value to an incorrect one occurs, Validation may pass it on one go and fail it the next). It's possible this is a race condition.

**Comment by PleasingFungus** [comment]
1. It's a description problem. Write-once memory's actual mechanic is "fail if an incorrect value is ever written to memory"; the flavor doesn't quite match that. I'll try to clear it up.

2. That's extremely worrying! I'll see if I can replicate that.

**Comment by KitsuneZeta** [comment]
From what PleasingFungus stated on the Steam thread, it appears problem 2 was a false issue caused by an update which changed the puzzle to actually be Write-Once Memory (Steam refuses to tell me there was ever an update), so that can be stricken from this issue.

Point 1 does still stand, the wording used in the game suggests that once a memory address has been written to it cannot be overwritten.

**Comment by PleasingFungus** [comment]
Fixed for the next release in 0b450620f8. Thanks for reporting!
