### ISSUE TITLE
Pressing Escape while testing jumps straight to puzzle selection

### ISSUE THREAD

**Issue by wellle** [PleasingFungus/Silicon-Zeroes#94]
Hey, I'm enjoying your game!

There's one thing that starts to get annoying though. When I want to switch from editing to testing, I click on the `Test` button. Once I see what's wrong I instinctively press the escape button to get back to editing my solution. What the game does instead is go back to the puzzle select. Now I'm thrown off because I need to select the puzzle again (which one was I just working on?) and then I'll have to hide the description overlay again to get some more place to work with (I'm using a small screen). And also it seems to forget my viewport, so I'll have to drag and potentially zoom back to where I was looking at. If that happens two or three times in a row it can get really frustrating.

I think there might be some potential for improvement by remembering my exact layout when getting back to a puzzle, but more importantly I think pressing Escape from within testing mode should not go back to puzzle select, but just back to editing the puzzle instead.

Thank you!

**Comment by PleasingFungus** [comment]
Changed 'escape' per request in d38c8116 (for next release). Viewport saving is a lot more work, so I'll hold off for now and see if this does the trick.

Thanks for reporting :)

**Comment by wellle** [comment]
Great 👍
