### ISSUE TITLE
mTick Par on Delay CPU

### ISSUE THREAD

**Issue by tomatosoupcan** [PleasingFungus/Silicon-Zeroes#96]
Just want to confirm that par on this is still 114, looking at issue #58 it looks like at that time par was 114, but the values for mTicks on some of those modules looks different than release. Running that exact setup from that issue produces 152 mTicks of time with 14 modules. Any optimizations in tick time appear to exist between the latch and instruction decoder but obviously adding a registry store there just causes a full tick delay and slows it down further. Might just be missing a more optimized solution.

**Comment by PleasingFungus** [comment]
Looks like you're right and this is out of date - I'll update it for the next version, thanks!

**Comment by PleasingFungus** [comment]
OK, fixed in e12e11ea & will be in the next update. Thanks again!
