### ISSUE TITLE
Sparkles appear before the end level pop-up

### ISSUE THREAD

**Issue by Pouf842** [PleasingFungus/Silicon-Zeroes#97]
When finishing a level, sparkles appear in the level area before the pop-up.

At least, they do on the few first levels, when reseting (Reset button) and calling back the last good solution (cup button).

**Comment by PleasingFungus** [comment]
Sparkles? Where?

**Comment by Pouf842** [comment]
Oh, sorry I wasn't clear : sparkles that appear besides the module number on the end level pop-up. You know :

Current : 16*
Best : 14*
Ideal : 14*

The "*" would be the sparkles.

**Comment by PleasingFungus** [comment]
Oh, haha! I'll take a look shortly.

**Comment by PleasingFungus** [comment]
Fixed in 2843bf00, thanks!
