### ISSUE TITLE
ERROR: trim path failure

### ISSUE THREAD

**Issue by Twisol** [PleasingFungus/Silicon-Zeroes#98]
![image](https://user-images.githubusercontent.com/61392/30968788-497f2326-a415-11e7-9aeb-5f4028477ac6.png)

I was moving a module on the "Branch" level when this happened. I had already solved the puzzle and was just prettifying the layout a bit when this happened.

**Comment by PleasingFungus** [comment]
Can you post your save file for the level? If you're on Windows, it'll be <INSTALLDIR>/profiles/profile0/saves/puzz-Branch.mftsv ; if on OS X, it's ~/Library/Application Support/Silicon Zeroes/profiles/profile0/saves/puzz-Branch.mftsv .

**Comment by Twisol** [comment]
Sure. (Added a false `.txt` extension to circumvent the attachment filetype filter. It _is_ plaintext, so maybe not as false as it seems...)

[puzz-Branch.mftsv.txt](https://github.com/PleasingFungus/Silicon-Zeroes/files/1341585/puzz-Branch.mftsv.txt)

**Comment by PleasingFungus** [comment]
Thanks! Will take a look shortly.

**Comment by PleasingFungus** [comment]
Was never able to reproduce anything with the attached save, but as the submitter notes, this is probably the same as #112.

**Comment by PleasingFungus** [comment]
Fixed in b58b24b3, hopefully.
